### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by MaxBondABE** [MaxBondABE/rusqlite_utils#1]
# Features
- [x] Create type for persisting `Duration`s
- [ ] Create a type for persisting encrypted secrets (such as passwords or API tokens)
- [ ] Create a type for using [`xid`](https://github.com/rs/xid) as the primary key scheme
- [ ] Create a macros for representing enums w/ all unit members as integer, text
- [ ] Enhance TryFromRow macro to use blob to represent BsonObject, JsonObject
- [ ] Add feature flags

# Documentation
- [ ] Add usage examples to README.md
- [ ] Enhance doc comments
- [ ] Create code examples

# Testing
- [ ] Improve unit test coverage
- [ ] Add property tests to detect unforeseen issues

# Administrative
- [ ] Complete Rust API Guidelines checklist
- [ ] Create a release candidate
- [ ] Solicit feedback
- [ ] Publish to crates.io
